### PR TITLE
Release23dev

### PR DESCRIPTION
**Pull request by bhillkeyfactor**

### CODE REVIEW

**Comment by bhillkeyfactor** [comment]
@fiddlermikey @rcpokorny @RexWheeler - Can you guys review this?  I had to go through a lot to get this to merge properly and wanted to make sure I did not miss anything....

**Review by rcpokorny — COMMENTED** [review]
Looks like the SQL code was added along with the updated ReadMe text.
One suggestion I would make (as this was done for WinCert) would be to make the Private Key Handling 'Optional' as opposed to 'Required'.  I'm not sure if that would make sense or not.

**Review by fiddlermikey — APPROVED** [review]
readme: Store Types and Stores detail sections added for new SQL Server types.

**Review by rcpokorny — APPROVED** [review]

**Comment by RexWheeler** [comment]
@fiddlermikey Looks like we have still lost the contents of PR88, those changes need to be included here (or at least end up in the release)

**Comment by rcpokorny** [comment]
I think I have to redo or reapply to the branch.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
